### ISSUE TITLE
list of user not coming  (me.list = []; --> list coming "Undefined")

### ISSUE THREAD

**Issue by ramkumarkushavah** [leota/electron-angular4-sqlite3#10]
Hi,

I am new with electron and knex platform.
I am using the same git repository.
All commands are running successfully. (Using window 10 platform)

But I am not getting any user list.
Q : I have to add user in sql or users list already present ???
      If present then list is not coming.
      if not then how to add the user list using app.component.ts file.

**Comment by leota** [comment]
Hi,

have a look at the `community` branch. There you can find an implementation on how to create a new community and save it to DB. Same procedure can be used to create new users.
Hope it helps :)

**Comment by ramkumarkushavah** [comment]
Thanks a lot. @leota 

It's working.
