### ISSUE TITLE
npm run rebuild error

### ISSUE THREAD

**Issue by dyh333** [leota/electron-angular4-sqlite3#12]
hi, @leota . I cloned your repo and run in local, but failed in npm run rebuild. could you tell me your npm version and python version and so on? thanks
![image](https://user-images.githubusercontent.com/1221313/45403473-1a23d500-b68d-11e8-8a98-67e5701f61d7.png)

**Comment by leota** [comment]
Hi @dyh333 ,
here my versions:

- npm 5.5.1
- python 2.7.13

**Note: ** I've node-gyp@3.6.2 globally installed. 
Please let me know if that works.

**Comment by leota** [comment]
Closing as it's not been active for several months.
