### ISSUE TITLE
Build fails on sqlite3 in Windows and Linux

### ISSUE THREAD

**Issue by tonydiep** [leota/electron-angular4-sqlite3#13]
npm i on Windows and Linux results in
```
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.13 install script.
```

**Comment by leota** [comment]
Hi @tonydiep , do you have `node-pre-gyp` globally installed?
if not, please try `npm i -g node-pre-gyp`

Let me know ;)

**Comment by tonydiep** [comment]
Hello @leota , node-pre-gyp is installed.

**Comment by leota** [comment]
@tonydiep great!! Thanks for your feedback, I'll update the `package.json`
