### ISSUE TITLE
Error: require is not defined in index.html

### ISSUE THREAD

**Issue by j4ys** [leota/electron-angular4-sqlite3#16]
at first, I followed as given instruction to start electron app but during npm install electron was failing to install.

then I removed the electron from package.json and manually installed electron with the latest version.

now I am getting an error saying that require is not defined in index.html file at line 15
`Uncaught ReferenceError: require is not defined
    at index.html:15`

and another error is cannot read property ipcRenderer of undefined in AppComponent
`AppComponent_Host.html:1 ERROR TypeError: Cannot read property 'ipcRenderer' of undefined`

**Comment by leota** [comment]
Hi @j4ys ,

do you have `node-gyp` globally installed? If not, can you please try `npm i -g node-gyp` and then try running `npm install` again with the original `package.json`?

Let me know

**Comment by j4ys** [comment]
I had node-gyp installed.
I tried with a fresh cloned copy but now electron window doesn't appear.

**Comment by leota** [comment]
What do you mean? Does it compile but the window does not appear?

**Comment by j4ys** [comment]
yes,
I changed show option in BrowserWindow constructor to true and now it's working
but why it doesn't work after updating electron to the latest version?

**Comment by leota** [comment]
Glad to hear you solved it.
BTW, I don't know why didn't work after electron update, probably it's not compatible with some other packages.

I'll try to make a new version with Angular 8 soon.
Thanks for pointing issues.

**Comment by j4ys** [comment]
thanks for this great repo.
I was struggling for a few days while setting up an electron app.

**Comment by j4ys** [comment]
just for general info,
I found why require doesn't work with the latest version of the electron 
from electron v5 `nodeIntegration` in electron is disabled by default so we need to enable it.

[stackoverflow reference](https://stackoverflow.com/questions/44391448/electron-require-is-not-defined)

**Comment by leota** [comment]
Great, this will definitely help when I'll upgrade all the packages. Thanks a lot!
