### ISSUE TITLE
how to get acces to DB folder created 

### ISSUE THREAD

**Issue by vibinmj** [leota/electron-angular4-sqlite3#3]
have a sqlite implemented for mobile app.wants to resuse it in my electron angular app,i was able to get the sqliteservice package in app.component.ts. but stuck in providing path to db,,,

  i tried like this..
this.db = window
.sqlitePlugin
.openDatabase({name: 'database.sqlite', location: ''../DB/''});
and this way:
    this.db = {name: 'database.sqlite', location: '../DB/'};

ant help would be appreciated..

**Comment by leota** [comment]
Electron is accessing DB, not Angular, it can't.

**Comment by vibinmj** [comment]
OK,thanks for your response,,how can i give path to get access to DB folder and write data to db and read it when in offline..?

**Comment by leota** [comment]
The DB path is specified in `src/electron/main.js`:
```
let knex = require("knex")({
  client: "sqlite3",
  connection: {
    filename: path.join(__dirname, '../DB/', 'database.sqlite')
  }
});
```
