### ISSUE TITLE
Maybe wrong path 

### ISSUE THREAD

**Issue by x5c** [leota/electron-angular4-sqlite3#5]
![gambar](https://user-images.githubusercontent.com/16497393/34287306-01f89f04-e719-11e7-9b98-76ee3fda90f1.png)

in my path directory to sqlite_node path
![gambar](https://user-images.githubusercontent.com/16497393/34287335-2c40919a-e719-11e7-8dd1-ab993ed7ee0b.png)

**Comment by leota** [comment]
Why are you runnig `npm install sqlite3 --save`?? Sqlite is already included in the `package.json`, you only need `npm install` whithin root directory to install all needed packages

**Comment by Ettemlevest** [comment]
@x5c for windows you need to install `electron-rebuild` module and run 
`./node_modules/.bin/electron-rebuild`
to build the required native module for electron.js.

See https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by x5c** [comment]
@Ettemlevest thats right guys, i think module was re generate
