### ISSUE TITLE
Is there any method to use sqlite3 or ORM directly in Angular Framework of the renderer process in Electron, not main process?

### ISSUE THREAD

**Issue by JeongJun-Lee** [leota/electron-angular4-sqlite3#6]
Is there any method to use sqlite3 or ORM directly in Angular Framework of the renderer process in Electron, not main process? Because the renderer process can understand Node'js APIs, I think it could be possible.

You can refer this issue https://github.com/typeorm/typeorm/issues/121.

Thank you.

**Comment by leota** [comment]
I don't think there is. ORM interact directly with DB, and, as far as I know, there's no chance to handle this on the client side.
