### ISSUE TITLE
Electron package for mac

### ISSUE THREAD

**Issue by deepkesh26** [leota/electron-angular4-sqlite3#9]
I am using this sample code and got success with local database things.
But my issue is when i am trying to make package for mac it is showing error. 
I am using electron-packager. I am attaching the screen shot of app when we are running angular-electron-sqlite.app file.

So can any one suggest how we can make it as package file 

<img width="420" alt="screen shot 2018-03-15 at 6 06 23 pm" src="https://user-images.githubusercontent.com/20107888/37463574-a6260c30-287b-11e8-9da4-c3db3ca2dfdc.png">

**Comment by leota** [comment]
Sorry @deepkesh26 , but I haven't tried using electron-packager. If you already found a solution to this please share it :)
